version: '3'
services:
  application:
    image: odoo:11
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-application-data:/var/lib/odoo
      - ./myaddons:/mnt/extra-addons
    networks:
        - aylin_odoo
    # command: --limit-time-cpu 2400 --limit-time-real 2400 -d aylin-odoo -u aylintech_changes
    # command: --limit-time-cpu 2400 --limit-time-real 2400 -d aylin-odoo
    command: --db-filter ^aylin-odoo -d aylin-odoo --limit-time-cpu 4800 --limit-time-real 4800
  db:
    image: postgres:latest
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
        - 5432
    # volumes:
    #     - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
        - aylin_odoo
    restart: always
volumes:
  odoo-application-data:
  # odoo-db-data:
networks:
    aylin_odoo:
        driver: bridge
