version: '3'
services:
  application:
    image: odoo:11
    depends_on:
      - db
    ports:
      - "8069:8069"
      # - "8072:8072"
    volumes:
      - odoo-application-data:/var/lib/odoo
      - ./myaddons:/mnt/extra-addons
    networks:
        - aylin_odoo
    # command: -d aylin-odoo --db-filter ^aylin --limit-time-cpu 2400 --limit-time-real 2400
  db:
    image: postgres:latest
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
        - 5432
    volumes:
        - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
        - aylin_odoo
    restart: always
  # nginx:
  #   image: nginx:latest
  #   ports:
  #       - 8069:80
  #   volumes:
  #       - ./default.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #       - aylin_odoo
  #   depends_on:
  #       - application
volumes:
  odoo-application-data:
  odoo-db-data:
networks:
    aylin_odoo:
        driver: bridge
