version: '3'
services:
  application:
    # image: odoo:11
    build: ./
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-application-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./myaddons:/mnt/myaddons
    networks:
        - aylin_odoo
    command: --db-filter aylin-odoo --limit-time-cpu 2400 --limit-time-real 2400
  db:
    image: postgres:latest
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
        - 5432
    volumes:
        - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
        - aylin_odoo
    restart: always
  # nginx:
  #     image: nginx:latest
  #     ports:
  #         - 8069:80
  #     volumes:
  #         - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #         - ./docker/logs/nginx:/var/log/nginx:rw
  #         - ./nginx:/opt/app:ro
  #     depends_on:
  #         - application
  #     networks:
  #         - aylin_odoo

volumes:
  odoo-application-data:
  odoo-db-data:
networks:
    aylin_odoo:
        driver: bridge
